import path from 'node:path';
import fs from 'node:fs/promises';
import { build } from 'vite';

const entryTag = '<script src="./landing.bundle.js"></script>';

async function createOfflineBundle(site) {
  const assets = new Set();
  const result = await build({
    configFile: false,
    publicDir: false,
    logLevel: 'error',
    plugins: [{
      name: 'offline-image-paths',
      enforce: 'pre',
      load(id) {
        if (!id.endsWith('.webp')) return null;
        assets.add(id);
        return `export default ${JSON.stringify(`./assets/${path.basename(id)}`)};`;
      },
    }],
    build: {
      write: false,
      minify: true,
      lib: { entry: path.join(site, 'landing.js'), name: 'SnapFlowLanding', formats: ['iife'] },
    },
  });
  const output = Array.isArray(result) ? result[0].output : result.output;
  const code = '// Generated by npm run build:website. Edit the source modules, then rebuild.\n'
    + output.find((item) => item.type === 'chunk').code;
  await fs.writeFile(path.join(site, 'landing.bundle.js'), code);
  return { code, assets: [...assets] };
}

export function offlineWebsitePlugins(root) {
  let bundle;
  return [
    {
      name: 'snapflow-offline-build',
      apply: 'build',
      async buildStart() { bundle = await createOfflineBundle(path.join(root, 'website')); },
      transformIndexHtml: {
        order: 'pre',
        handler: (html) => html.replace(entryTag, ''),
      },
      async generateBundle() {
        this.emitFile({ type: 'asset', fileName: 'landing.bundle.js', source: bundle.code });
        for (const asset of bundle.assets) {
          this.emitFile({ type: 'asset', fileName: `assets/${path.basename(asset)}`, source: await fs.readFile(asset) });
        }
      },
    },
    {
      name: 'snapflow-offline-entry',
      apply: 'build',
      transformIndexHtml: {
        order: 'post',
        handler: (html, context) => context.path === '/index.html'
          ? [{ tag: 'script', attrs: { src: './landing.bundle.js' }, injectTo: 'body' }]
          : html,
      },
    },
    {
      name: 'snapflow-live-development',
      apply: 'serve',
      transformIndexHtml: {
        order: 'pre',
        handler: (html) => html.replace(entryTag, '<script type="module" src="./landing.js"></script>'),
      },
    },
  ];
}
