export const english = {
  themeLabel: 'Color theme', themeSystem: 'System', themeLight: 'Light', themeDark: 'Dark',
  skip: 'Skip to content', navLabel: 'Main navigation', homeLabel: 'SnapFlow — home',
  navFlow: 'How it works', navFeatures: 'Features', navField: 'In the field', navStart: 'Get started', menuLabel: 'Open menu',
  heroEyebrow: 'YOUR TALENT DESERVES A BETTER FLOW', heroLine1: 'Live the moment.', heroLine2: 'Let the rest', heroLine3: 'flow.',
  heroDescription: 'From the first shot to the final delivery. Galleries, sales, and payments in one place, so you can focus on what you do best.',
  heroCta: 'Try it in action', heroSecondary: 'See how it works', heroNote: 'Made for photographers. Built for the real world.',
  artCaption: 'FEWER STEPS. MORE MOMENTS.', heroAlt: 'A floating 3D camera surrounded by beach, couple, and event photographs',
  heroPayment: 'Pix confirmed', heroDelivery: 'All set. Photos unlocked.', heroGallery: 'Your vision, your brand.', heroGallerySub: 'A gallery with your signature.', artFootnote: 'FROM CAPTURE TO DELIVERY ↗',
  areasLabel: 'Photography settings', stripTitle: 'WHEREVER THERE’S A STORY, THERE’S ROOM FOR SNAPFLOW.', tourism: 'Travel', events: 'Events', portraits: 'Portraits', schools: 'Schools', experiences: 'Experiences',
  flowEyebrow: 'ONE FLOW. FROM START TO FINISH.', flowTitle1: 'Your next shot.', flowTitle2: 'Your next sale.', flowIntro: 'The magic is in your vision. We’ll help with the organization. Connect every step without slowing down your session.',
  demoEyebrow: 'EXPERIENCE THE FLOW', demoTitle1: 'Your client chooses.', demoTitle2: 'It all comes together.', demoTitle3: 'You keep creating.',
  demoText: 'An effortless experience for your clients. More control for you. Select a few photos and watch the flow come to life.', demoStepsLabel: 'Demo steps', demoDisclaimer: 'Interactive demo · No charges or data submitted.', privateGallery: 'private gallery',
  featuresEyebrow: 'LESS ADMIN. MORE PHOTOGRAPHY.', featuresTitle1: 'Everything works together.', featuresTitle2: 'For your creative freedom.', featuresIntro: 'Tools that make a difference between one client and the next. Keeping the simple things simple.',
  fieldEyebrow: 'MADE FOR LIFE OUT THERE', fieldTitle1: 'Your studio is', fieldTitle2: 'where life happens.', fieldIntro: 'On the beach, at the celebration, on the next great adventure. Bring a professional process wherever your vision takes you.',
  sceneNote: 'For schools, parks, graduations, and corporate events, too. One flow, so many possibilities.',
  faqEyebrow: 'BEFORE YOUR NEXT SHOT', faqTitle: 'A few things to know.', faqIntro: 'The details behind a smoother workflow.',
  closingEyebrow: 'MORE PRESENCE. LESS TO-DO.', closingLine1: 'Your vision makes the difference.', closingLine2: 'Give it a flow that keeps up.', closingCta: 'Get started with SnapFlow', closingNote: 'From photography to payment. From one sale to the next story.',
  footerTagline: 'A good eye deserves a great flow.', footerPortfolio: 'View portfolio (PT)', footerHelp: 'FAQ', footerMade: 'Created in Brazil. Made for your next shot.', backTop: 'Back to top ↑',
  closeLabel: 'Close', startEyebrow: 'YOUR NEXT STEP', startTitle: 'Let’s get your workflow moving.', startText: 'SnapFlow runs on your own setup. The project guide takes you from initial configuration to your first gallery.',
  startItem1: 'Prepare Windows, Node.js, and PostgreSQL.', startItem2: 'Run the project’s guided installer.', startItem3: 'Set up your pricing, Pix, and public access.', startGuide: 'Open installation guide (PT)', startDemo: 'I’d like to explore the demo first',
};

export const content = {
  'pt-BR': {
    title: 'SnapFlow — Do clique à entrega.', description: 'Do clique à entrega. SnapFlow conecta galerias, seleção de fotos, pagamento por Pix e downloads em um fluxo feito para fotógrafos em campo.',
    steps: [
      ['Capture e organize', 'Envie suas fotos e crie uma galeria privada. Sua marca, seus pacotes, suas regras.'],
      ['Encante e venda', 'O cliente escolhe as favoritas no próprio celular e paga por Pix. Simples assim.'],
      ['Entregue e siga criando', 'Pagamento aprovado, downloads liberados. O próximo momento já está esperando.'],
    ],
    demoSteps: [['Escolha suas favoritas', 'Uma galeria feita para o celular.'], ['Pague do seu jeito', 'Pix, dinheiro ou cartão.'], ['Leve o momento com você', 'Fotos disponíveis após a aprovação.']],
    features: [
      ['IDENTIDADE', 'Sua galeria. Sua assinatura.', 'Marcas d’água, overlays e links personalizados. Uma apresentação que valoriza seu trabalho, com código de acesso e validade sob seu controle.'],
      ['VENDAS', 'Um bom momento vale mais.', 'Crie pacotes, ajuste preços e aplique descontos. O cálculo acompanha a seleção para você vender com clareza, sem fazer contas no meio do atendimento.'],
      ['ENTREGA', 'Entregue fotos. Não trabalho.', 'Download individual ou de tudo em ZIP. Aviso por WhatsApp e envio de originais como documento são opcionais. A entrega pela galeria segue independente.'],
      ['CONTROLE', 'Clareza para o próximo passo.', 'Acompanhe vendas, pagamentos e o funil de conversão. Veja o que está pendente, aprove dinheiro e cartão e gerencie suas galerias no mesmo painel.'],
    ],
    visuals: { brand: 'SEU OLHAR ®', protected: 'Prévias protegidas', single: 'Foto avulsa', pack: 'Pacote de 3 fotos', rules: 'Seu preço. Suas regras.', prices: 'Valores ilustrativos', ready: 'Memórias prontas.', quality: 'Qualidade em cada arquivo.', operation: 'Sua operação, à vista', chart: 'Visualização ilustrativa' },
    scenes: [
      ['coast', 'Casal caminhando de mãos dadas em uma praia de Alagoas', 'TURISMO & EXPERIÊNCIAS', 'A viagem passa.\nA lembrança fica.', 'Crie a galeria do passeio, compartilhe o link e deixe cada cliente escolher no próprio celular.'],
      ['events', 'Convidados celebrando em um evento ao ar livre sob luzes quentes', 'EVENTOS & CELEBRAÇÕES', 'O evento não para.\nSeu fluxo também não.', 'Organize fotos por cliente, ofereça pacotes e acompanhe cada aprovação sem perder a próxima cena.'],
    ],
    sceneCta: 'Experimente o fluxo',
    faqs: [
      ['Meu cliente precisa instalar um aplicativo?', 'Não. O cliente acessa o link da galeria no navegador, informa o código de acesso e escolhe suas fotos. Depois da aprovação do pagamento, os downloads ficam disponíveis na própria galeria.'],
      ['Como funcionam os pagamentos?', 'O Pix usa a integração com o Mercado Pago. Após a confirmação chegar ao SnapFlow, as fotos compradas são liberadas automaticamente. Dinheiro e cartão exigem aprovação explícita no painel; a cobrança no cartão é feita por fora do sistema.'],
      ['A entrega depende do WhatsApp?', 'Não. As fotos compradas ficam disponíveis para download na galeria, individualmente ou em ZIP. Você pode ativar avisos e o envio adicional dos originais pelo WhatsApp. Uma falha nesse canal não bloqueia o download.'],
      ['Posso usar minhas marcas e meus preços?', 'Sim. Configure pacotes, preços e descontos, use marcas d’água e overlays próprios e personalize os links. Você também controla a validade de acesso; o prazo padrão após o pagamento é de 7 dias e pode ser ajustado.'],
      ['Do que preciso para começar?', 'A instalação atual usa Windows, Node.js e PostgreSQL. O projeto inclui um instalador guiado. Para Pix real, configure sua conta Mercado Pago e um webhook público. Para galerias acessíveis aos clientes, disponibilize o serviço na internet. Consulte o guia de instalação para todos os requisitos.'],
    ],
    demo: {
      location: 'ALAGOAS, BRASIL', title: 'Um dia para guardar.', subtitle: 'Escolha os seus momentos favoritos.', badge: 'GALERIA DEMONSTRATIVA',
      photoLabels: ['Passeio à beira-mar', 'Detalhes da costa', 'Um encontro especial'], select: 'Selecionar foto', selected: 'selecionadas',
      priceHint: 'R$ 25 por foto · A partir de 3, R$ 20 cada', total: 'Total', continue: 'Continuar', choose: 'Selecione uma foto para continuar.',
      paymentTitle: 'Quase suas.', paymentSubtitle: 'Escolha como simular o pagamento.', pix: 'Pix', pixHint: 'Liberação após a confirmação', manual: 'Dinheiro / cartão', manualHint: 'Aprovação do fotógrafo',
      simulation: 'Simulação — nenhum pagamento será gerado.', pay: 'Simular confirmação do Pix', request: 'Solicitar aprovação', pending: 'Aguardando o fotógrafo', pendingText: 'Na operação real, o administrador precisa aprovar dinheiro ou cartão antes de liberar as fotos.', approve: 'Simular aprovação do fotógrafo',
      back: 'Voltar para as fotos', done: 'O momento agora é seu.', doneSub: 'Pagamento simulado aprovado. Suas fotos estão liberadas nesta demonstração.', download: 'Baixar amostra', downloadNote: 'Amostras ilustrativas em WebP. Na galeria real, baixe suas fotos finais ou tudo em ZIP.', restart: 'Experimentar novamente', summary: 'Resumo da seleção',
    },
  },
  en: {
    title: 'SnapFlow — From capture to delivery.', description: 'From capture to delivery. SnapFlow connects galleries, photo selection, Pix payments, and downloads in one workflow for photographers in the field.',
    steps: [
      ['Capture and organize', 'Upload your photos and create a private gallery. Your brand, your packages, your rules.'],
      ['Inspire and sell', 'Your client chooses their favorites on their own phone and pays with Pix. Just like that.'],
      ['Deliver and keep creating', 'Payment approved, downloads unlocked. Your next moment is already waiting.'],
    ],
    demoSteps: [['Choose your favorites', 'A gallery made for mobile.'], ['Pay your way', 'Pix, cash, or card.'], ['Take the moment with you', 'Photos unlocked after approval.']],
    features: [
      ['IDENTITY', 'Your gallery. Your signature.', 'Watermarks, overlays, and custom links. A presentation that values your work, with access codes and expiration dates under your control.'],
      ['SALES', 'Make a great moment worth more.', 'Create packages, adjust prices, and apply discounts. Totals follow the selection, so you can sell with confidence without doing math between clients.'],
      ['DELIVERY', 'Deliver photos. Not more work.', 'Individual downloads or everything in a ZIP. WhatsApp notifications and original files sent as documents are optional. Gallery delivery stays independent.'],
      ['CONTROL', 'Clarity for your next step.', 'Track sales, payments, and your conversion funnel. See what’s pending, approve cash and card payments, and manage galleries in one dashboard.'],
    ],
    visuals: { brand: 'YOUR VISION ®', protected: 'Protected previews', single: 'Single photo', pack: '3-photo package', rules: 'Your prices. Your rules.', prices: 'Illustrative prices in BRL', ready: 'Memories, ready.', quality: 'Quality in every file.', operation: 'Your business at a glance', chart: 'Illustrative visualization' },
    scenes: [
      ['coast', 'A couple walking hand in hand on a beach in Alagoas, Brazil', 'TRAVEL & EXPERIENCES', 'The trip ends.\nThe memory stays.', 'Create a gallery for the trip, share the link, and let each client choose on their own phone.'],
      ['events', 'Guests celebrating an outdoor event beneath warm string lights', 'EVENTS & CELEBRATIONS', 'The event keeps going.\nSo does your flow.', 'Organize photos by client, offer packages, and track every approval without missing the next scene.'],
    ],
    sceneCta: 'Experience the flow',
    faqs: [
      ['Does my client need to install an app?', 'No. Clients open the gallery link in their browser, enter the access code, and choose their photos. Once payment is approved, downloads become available in the same gallery.'],
      ['How do payments work?', 'Pix, Brazil’s instant payment method, connects through Mercado Pago. Once confirmation reaches SnapFlow, purchased photos unlock automatically. Cash and card payments require explicit approval in the dashboard; card charges are processed outside SnapFlow.'],
      ['Does delivery depend on WhatsApp?', 'No. Purchased photos are available in the gallery, individually or as a ZIP. You can enable notifications and optional original-file delivery through WhatsApp. An issue with that channel never blocks gallery downloads.'],
      ['Can I use my own branding and prices?', 'Yes. Configure packages, prices, and discounts, add your watermarks and overlays, and personalize gallery links. You also control access expiration; the default post-payment window is 7 days and can be adjusted.'],
      ['What do I need to get started?', 'The current installation runs on Windows, Node.js, and PostgreSQL. The project includes a guided installer. Real Pix payments require your Mercado Pago account and a public webhook. For client access, make your gallery service available online. See the installation guide for all requirements.'],
    ],
    demo: {
      location: 'ALAGOAS, BRAZIL', title: 'A day to remember.', subtitle: 'Choose your favorite moments.', badge: 'DEMO GALLERY',
      photoLabels: ['A walk by the sea', 'Details of the coast', 'A special celebration'], select: 'Select photo', selected: 'selected',
      priceHint: 'R$25 per photo · 3 or more: R$20 each', total: 'Total', continue: 'Continue', choose: 'Select a photo to continue.',
      paymentTitle: 'Almost yours.', paymentSubtitle: 'Choose how to simulate your payment.', pix: 'Pix', pixHint: 'Unlocks after confirmation', manual: 'Cash / card', manualHint: 'Photographer approval required',
      simulation: 'Simulation — no payment will be created.', pay: 'Simulate Pix confirmation', request: 'Request approval', pending: 'Waiting for the photographer', pendingText: 'In the real workflow, the administrator must approve cash or card payments before photos are released.', approve: 'Simulate photographer approval',
      back: 'Back to photos', done: 'The moment is yours.', doneSub: 'Simulated payment approved. Your photos are unlocked in this demo.', download: 'Download sample', downloadNote: 'Illustrative WebP samples. In a real gallery, download final photos individually or in a ZIP.', restart: 'Try it again', summary: 'Selection summary',
    },
  },
};
